edu:
    USER_ID: 
    USER_KEY: 
mashov:
#Add Kids Block as needed (please enclose with "" , for example "123456")
#UNused Kid Block should be commented with # or removed from file
    kid1:
        MASHOV_USER_ID_KID: 
        MASHOV_USER_PWD_KID: 
        MASHOV_SCHOOL_ID_KID: 
    #kid2:
    #    MASHOV_USER_ID_KID: 
    #    MASHOV_USER_PWD_KID: 
    #    MASHOV_SCHOOL_ID_KID: 
infogan:
    BASE_URL: 
    PARENT_NAME: 
    PARENT_ID: 
    KID_NAME: 
    KID_ID: 